server:
  port: 8081

spring:
  datasource:
    url: jdbc:mariadb://${AI_DB_HOST}:3306/ai_db?characterEncoding=UTF-8&serverTimezone=Asia/Seoul&sslMode=trust
    username: ${AI_DB_USERNAME}
    password: ${AI_DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zone: Asia/Seoul

#모델 url
ai-fastapi:
  url: ${FASTAPI_URL:http://localhost:8000}

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.sanavi.aiapi
  configuration:
    map-underscore-to-camel-case: true
